main:
	g++ -O2 -Wall -Wextra -std=c++11 -pedantic \
		main.cpp \
		ui/mainui.cpp \
		exceptions/FileExistsException.cpp \
		exceptions/FileReadException.cpp \
		exceptions/FileWriteException.cpp \
	-o out.exe
