main:
	g++ -O2 -Wall -Wextra -std=c++11 -pedantic \
		main.cpp \
		models/base.cpp \
		models/topping.cpp \
		models/pizza.cpp \
		ui/mainui.cpp \
		ui/management.cpp \
		repositories/baseio.cpp \
		repositories/toppingio.cpp \
		repositories/menuio.cpp \
		services/managementservice.cpp \
		exceptions/FileExistsException.cpp \
		exceptions/FileReadException.cpp \
		exceptions/FileWriteException.cpp \
	-o out.exe
