main:
	g++ -O2 -Wall -Wextra -std=c++11 -pedantic \
		main.cpp \
		models/base.cpp \
		models/topping.cpp \
		models/product.cpp \
		models/pizza.cpp \
		models/orderdetails.cpp \
		models/order.cpp \
		ui/mainui.cpp \
		ui/management.cpp \
		ui/delivery.cpp \
		ui/preperation.cpp \
		ui/ordering.cpp \
		repositories/baseio.cpp \
		repositories/toppingio.cpp \
		repositories/menuio.cpp \
		repositories/locationio.cpp \
		repositories/productio.cpp \
		repositories/orderio.cpp \
		services/managementservice.cpp \
		services/orderservice.cpp \
		exceptions/FileExistsException.cpp \
		exceptions/FileReadException.cpp \
		exceptions/FileWriteException.cpp \
	-o out.exe
