main:
	g++ -O2 -Wall -Wextra -std=c++11 -pedantic \
		main.cpp \
		models/salary.cpp \
		ui/mainui.cpp \
		services/salaryservice.cpp \
		repositories/recordwriter.cpp \
		repositories/recordreader.cpp \
		exceptions/EmployeeNameException.cpp \
		exceptions/EmployeeMonthException.cpp \
		exceptions/EmployeeSalaryException.cpp \
		exceptions/EmployeeSSNException.cpp \
		exceptions/EmployeeYearException.cpp \
		exceptions/FileExistsException.cpp \
		exceptions/FileReadException.cpp \
		exceptions/FileWriteException.cpp \
	-o out.exe
